Repository louislam/uptime-kuma, pull requests merged in 2024-03, with the labels that each got.

#4525 More readable Contribution guide
  CONTRIBUTING.md
Labels: doc, house keeping

#4521 migrate timezones-list lib to @vvo/tzdb issue #4479
  package-lock.json
  package.json
  src/util-frontend.js
Labels: area:core, house keeping

#4472 Fix: handle monitor names with slashes
  server/model/monitor.js
  src/pages/Details.vue
  src/pages/EditMonitor.vue
Labels: area:monitor

#4527 Updated strings for `LINE Messenger` as changed in their developer portal
  src/components/notifications/Line.vue
  src/lang/en.json
Labels: area:notifications

#4411 [Ntfy] Only include action link if monitor url is defined #3274
  server/notification-providers/ntfy.js
Labels: area:notifications

#4477 Improved helptext of how to send mail via the systems mail subsystem
  src/components/notifications/SMTP.vue
  src/lang/en.json
Labels: area:ui/ux

#4485 Add Heii On-Call Notification Provider
  server/notification-providers/heii-oncall.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/HeiiOnCall.vue
  src/components/notifications/index.js
  src/lang/en.json
Labels: area:notifications

#3182 Chore: General notification reformatting
  server/monitor-types/monitor-type.js
  server/notification-providers/alerta.js
  server/notification-providers/alertnow.js
  server/notification-providers/aliyun-sms.js
  server/notification-providers/apprise.js
  server/notification-providers/bark.js
  server/notification-providers/clicksendsms.js
  server/notification-providers/dingding.js
  server/notification-providers/discord.js
  server/notification-providers/feishu.js
  server/notification-providers/freemobile.js
  server/notification-providers/goalert.js
  server/notification-providers/google-chat.js
  server/notification-providers/gorush.js
  server/notification-providers/gotify.js
  server/notification-providers/grafana-oncall.js
  server/notification-providers/home-assistant.js
  server/notification-providers/kook.js
  server/notification-providers/line.js
  server/notification-providers/linenotify.js
  server/notification-providers/lunasea.js
  server/notification-providers/matrix.js
  server/notification-providers/mattermost.js
  server/notification-providers/ntfy.js
  server/notification-providers/octopush.js
  server/notification-providers/onebot.js
  server/notification-providers/opsgenie.js
  server/notification-providers/promosms.js
  server/notification-providers/pushbullet.js
  server/notification-providers/pushdeer.js
  server/notification-providers/pushover.js
  server/notification-providers/pushy.js
  server/notification-providers/rocket-chat.js
  server/notification-providers/serverchan.js
  server/notification-providers/serwersms.js
  server/notification-providers/signal.js
  server/notification-providers/slack.js
  server/notification-providers/smsc.js
  server/notification-providers/smseagle.js
  server/notification-providers/smsmanager.js
  server/notification-providers/smtp.js
  server/notification-providers/squadcast.js
  server/notification-providers/stackfield.js
  server/notification-providers/teams.js
  server/notification-providers/techulus-push.js
  server/notification-providers/telegram.js
  server/notification-providers/twilio.js
  server/notification-providers/webhook.js
  server/notification-providers/wecom.js
  server/notification-providers/zoho-cliq.js
Labels: area:notifications

#4592 made sure to use `Promise.allSettled` instead of sleeping for 500ms after login
  server/server.js
Labels: house keeping

#4541 add notification channel for home assistant
  server/notification-providers/home-assistant.js
Labels: question, area:notifications

#3928 Google chat cards
  server/notification-providers/google-chat.js
Labels: area:notifications

#4406 Feat: Handle maintenance in `UptimeCalculator`
  db/knex_migrations/2024-01-22-0000-stats-extras.js
  server/uptime-calculator.js
Labels: area:maintenance, area:metrics

#4632 Fix: Add missing FK for monitor-tls-info table
  db/knex_init_db.js
  db/old_migrations/patch-monitor-tls-info-add-fk.sql
  server/database.js
Labels: area:core

#4631 Fix: Add missing FK for monitor-tls-info table [1.23.X]
  db/patch-monitor-tls-info-add-fk.sql
  server/database.js
Labels: area:core
