Repository louislam/uptime-kuma, pull requests merged in 2024-01, with the labels that each got.

#4267 Feat: Add `stat_hourly` & min. max. ping
  db/knex_migrations/2023-12-21-0000-stat-ping-min-max.js
  db/knex_migrations/2023-12-22-0000-hourly-uptime.js
  server/uptime-calculator.js
  test/backend-test/test-uptime-calculator.js
Labels: area:metrics, area:core

#4322 Fix incorrect ping log
  server/util-server.js
Labels: area:monitor

#4326 Fix `encodeBase64` for empty password or user in HTTP Basic Authentication
  server/model/monitor.js
Labels: area:monitor

#4296 Moving the server
  README.md
Labels: area:deployment

#4244 made sure that the i18n does use `navigator.languages` instead of `navigator.language` for automatic language detection
  src/i18n.js
  test/cypress/unit/i18n.spec.js
Labels: bug, area:core

#4320 Corrected "Login" & "Logout" to verbs (EN)
  src/lang/en.json
  test/e2e/setup.spec.js
  test/e2e/util-test.js
Labels: question, area:core

#3598 fix(notification-dingding): throw error when failed
  server/notification-providers/dingding.js
Labels: area:notifications

#4240 chore/issue template modification for v2
  .github/ISSUE_TEMPLATE/ask-for-help.yaml
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: area:core

#4331 Feat: Show monitor ID in Details
  src/assets/vars.scss
  src/components/HeartbeatBar.vue
  src/pages/Details.vue
  src/pages/Settings.vue
Labels: area:monitor, area:ui/ux
