Repository louislam/uptime-kuma, pull requests merged in 2024-06, with the labels that each got.

#4494 Feat: Add background color change on hover to nav links
  src/layouts/Layout.vue
Labels: area:dashboard

#4476 Fix: Use `retryInterval` when a monitor is `DOWN`
  server/model/monitor.js
Labels: area:monitor, needs:review

#4816 Fixed `smspartner` not having fully working translations
  src/components/notifications/SMSPartner.vue
Labels: house keeping, needs:review

#4819 Removed the last reminents of `cypress`
  .dockerignore
  .eslintrc.js
  config/cypress.config.js
  config/cypress.frontend.config.js
Labels: house keeping, needs:review

#4820 removed some monitor drift in terms of code comments
  server/monitor-types/dns.js
  server/monitor-types/mongodb.js
  server/monitor-types/monitor-type.js
  server/monitor-types/mqtt.js
  server/monitor-types/tailscale-ping.js
Labels: area:monitor, house keeping, needs:review

#4848 improved zoho-cliq message format
  server/notification-providers/discord.js
  server/notification-providers/notification-provider.js
  server/notification-providers/sevenio.js
  server/notification-providers/smtp.js
  server/notification-providers/squadcast.js
  server/notification-providers/teams.js
  server/notification-providers/zoho-cliq.js
Labels: area:notifications, type:enhance-existing, needs:work

#4854 New notification provider: Threema Gateway
  server/notification-providers/threema.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/Threema.vue
  src/components/notifications/index.js
  src/lang/en.json
Labels: area:notifications, type:new, needs:work

#4877 Update dependencies and embed axios-ntlm 1.3.0 into the project
  .eslintrc.js
  package-lock.json
  package.json
  server/modules/axios-ntlm/LICENSE
  server/modules/axios-ntlm/lib/flags.js
  server/modules/axios-ntlm/lib/hash.js
  server/modules/axios-ntlm/lib/ntlm.js
  server/modules/axios-ntlm/lib/ntlmClient.js
  server/util-server.js
Labels: area:monitor, type:enhance-existing

#4871 Fix Slack notifications when URL is present
  server/notification-providers/slack.js
Labels: area:notifications, type:enhance-existing, needs:work
