Repository louislam/uptime-kuma, pull requests merged in 2024-04, with the labels that each got.

#3886 [Slack] restructure alert actions, add 'visit site' button
  server/notification-providers/slack.js
Labels: area:notifications

#4605 New notification provider: CallMeBot API
  server/notification-providers/call-me-bot.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/CallMeBot.vue
  src/components/notifications/index.js
  src/lang/en.json
Labels: question, area:notifications

#4630 Feat: Use keylog event to obtain TLS certificate for better reliability [1.23.X]
  server/model/monitor.js
  server/util-server.js
Labels: area:cert-expiry

#4666 Update i18n.js
  src/i18n.js
Labels: area:core

#4668 Update CONTRIBUTING.md for how to set up a Docker builder
  CONTRIBUTING.md
Labels: area:documentation

#4636 Add `loginRequired` SocketIO event
  server/server.js
  src/mixins/socket.js
Labels: area:api, area:core

#4700 Fix: Getting TLS certificate through proxy & prometheus update
  server/model/monitor.js
  server/prometheus.js
Labels: area:monitor, area:cert-expiry

#4718 Add the ability to notify `@everyone` in DingTalk notifications
  server/notification-providers/dingding.js
  src/components/notifications/DingDing.vue
  src/lang/en.json
Labels: area:notifications, type:enhance-existing

#4219 SevenIO Notification Provider
  server/notification-providers/sevenio.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/SevenIO.vue
  src/components/notifications/index.js
  src/lang/en.json
Labels: area:notifications

#4723 Fix: Show API Keys disabled msg. when disabled Auth
  src/components/settings/APIKeys.vue
  src/lang/en.json
Labels: area:documentation

#3836 Making docker usage with localhost and external ip more clear
  README.md
Labels: area:documentation
