Repository louislam/uptime-kuma, pull requests merged in 2024-08, with the labels that each got.

#4971 Add OneSender Webhook notification
  server/notification-providers/onesender.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/Onesender.vue
  src/components/notifications/index.js
  src/lang/en.json
Labels: area:notifications, needs:work

#4704 Extend Prometheus Labels to include tags (requires restart for NEW labels on the monitor to be visible)
  server/model/monitor.js
  server/prometheus.js
Labels: help wanted, question, area:metrics, pr:needs review

#4813 Add translation key for `time ago`
  src/components/HeartbeatBar.vue
  src/lang/en.json
Labels: area:dashboard, house keeping, pr:needs review

#4376 Extend length of status bars in status page
  src/components/PublicGroupList.vue
Labels: area:status-page, pr:needs review

#4815 Removed now unnecessary version checking
  package.json
  server/notification-providers/nostr.js
  server/server.js
  test/backend-test-entry.js
  test/backend-test/README.md
  test/backend-test/test-uptime-calculator.js
Labels: releaseblocker, house keeping, pr:needs review

#4818 made sure that the socket handlers have consitent names
  server/server.js
  server/socket-handlers/database-socket-handler.js
  server/socket-handlers/general-socket-handler.js
Labels: house keeping, pr:needs review

#4193 Fix: name column in the dashboad being squashed in some aspect ratios
  src/pages/DashboardHome.vue
Labels: area:dashboard, area:ui/ux, pr:needs review

#3525 Add option to pass cache bust param
  db/knex_migrations/2024-08-24-000-add-cache-bust.js
  server/model/monitor.js
  server/server.js
  src/lang/en.json
  src/pages/EditMonitor.vue
Labels: question, area:monitor, pr:please address review comments

#5056 Improve Playwright/E2E testing setup
  config/playwright.config.js
  server/server.js
  test/e2e/setup.spec.js
  test/e2e/specs/example.spec.js
  test/e2e/specs/setup-process.once.js
  test/e2e/util-test.js
Labels: pr:please address review comments

#5058 New Notification Provider SIGNL4
  server/notification-providers/signl4.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/SIGNL4.vue
  src/components/notifications/index.js
  src/lang/en.json
Labels: area:notifications, type:new, pr:please address review comments

#5053 fix: undefined in log while creating a new monitor
  server/server.js
Labels: area:monitor, area:deployment, pr:please address review comments

#5048 Monitor Conditions
  db/knex_migrations/2024-08-24-0000-conditions.js
  server/client.js
  server/model/monitor.js
  server/monitor-conditions/evaluator.js
  server/monitor-conditions/expression.js
  server/monitor-conditions/operators.js
  server/monitor-conditions/variables.js
  server/monitor-types/dns.js
  server/monitor-types/monitor-type.js
  server/server.js
  src/components/EditMonitorCondition.vue
  src/components/EditMonitorConditionGroup.vue
  src/components/EditMonitorConditions.vue
  src/lang/en.json
  src/mixins/socket.js
  src/pages/Details.vue
  src/pages/EditMonitor.vue
  test/backend-test/monitor-conditions/test-evaluator.js
  test/backend-test/monitor-conditions/test-expressions.js
  test/backend-test/monitor-conditions/test-operators.js
  test/e2e/specs/monitor-form.spec.js
Labels: area:monitor, type:enhance-existing, pr:please address review comments
