Repository louislam/uptime-kuma, pull requests merged in 2024-10, with the labels that each got.

#5149 tests: improve playwright test readability
  test/e2e/specs/monitor-form.spec.js
  test/e2e/specs/setup-process.once.js
  test/e2e/specs/status-page.spec.js
Labels: area:core, pr:please address review comments

#4814 Better description for shrink database button
  src/components/settings/MonitorHistory.vue
  src/lang/ar-SY.json
  src/lang/ar.json
  src/lang/bg-BG.json
  src/lang/cs-CZ.json
  src/lang/da-DK.json
  src/lang/de-CH.json
  src/lang/de-DE.json
  src/lang/el-GR.json
  src/lang/en.json
  src/lang/es-ES.json
  src/lang/eu.json
  src/lang/fa.json
  src/lang/fi.json
  src/lang/fr-FR.json
  src/lang/ga.json
  src/lang/he-IL.json
  src/lang/hr-HR.json
  src/lang/hu.json
  src/lang/id-ID.json
  src/lang/it-IT.json
  src/lang/ja.json
  src/lang/ko-KR.json
  src/lang/nl-NL.json
  src/lang/pl.json
  src/lang/pt-BR.json
  src/lang/pt-PT.json
  src/lang/ro.json
  src/lang/ru-RU.json
  src/lang/sl-SI.json
  src/lang/sv-SE.json
  src/lang/te.json
  src/lang/th-TH.json
  src/lang/tr-TR.json
  src/lang/uk-UA.json
  src/lang/ur.json
  src/lang/vi-VN.json
  src/lang/zh-CN.json
  src/lang/zh-HK.json
  src/lang/zh-TW.json
Labels: house keeping, pr:needs other pr merged

#3256 fix: Both `Add` and `Home` being shown as selected on the homescreen
  src/router.js
Labels: area:dashboard, pr:needs review

#5152 feat: monitor debug curl
  src/lang/en.json
  src/pages/EditMonitor.vue
Labels: area:monitor, area:dashboard, pr:please address review comments

#5025 improve page load performance of large amount urls
  server/model/monitor.js
  server/server.js
  server/uptime-kuma-server.js
  src/mixins/socket.js
  src/pages/EditMonitor.vue
  src/util.js
Labels: area:api, pr:needs review

#5167 [slack] allow the user to choose the message format to send
  server/notification-providers/slack.js
  src/components/notifications/Slack.vue
  src/lang/en.json
Labels: area:notifications, pr:please address review comments

#5164 refactor: removed unnecessary todo comment, modified jsdoc of utility func
  server/notification-providers/dingding.js
  src/util.js
  src/util.ts
Labels: question

#5178 feat: support sound and title in `TechulusPush`
  server/notification-providers/techulus-push.js
  src/components/notifications/TechulusPush.vue
  src/lang/en.json
Labels: area:notifications, pr:please address review comments

#5184 feat: new notification provider `46elks`
  server/notification-providers/46elks.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/46elks.vue
  src/components/notifications/index.js
  src/lang/en.json
Labels: area:notifications, type:new, pr:please address review comments

#5196 fix: some errors from the performance optimization
  server/model/monitor.js
Labels: area:monitor, pr:please address review comments

#4451 tests: add testcase for the mqtt monitor with testcontainers
  package-lock.json
  package.json
  test/backend-test/test-mqtt.js
Labels: area:monitor, pr:please address review comments

#5205 feat: add notification provider `SendGrid`
  server/notification-providers/send-grid.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/SendGrid.vue
  src/components/notifications/index.js
  src/lang/en.json
Labels: area:notifications, type:new, pr:please address review comments

#5199 feat: add `RabbitMQ` monitor
  db/knex_migrations/2024-10-1315-rabbitmq-monitor.js
  package-lock.json
  package.json
  server/model/monitor.js
  server/monitor-types/rabbitmq.js
  server/server.js
  server/uptime-kuma-server.js
  src/lang/en.json
  src/pages/EditMonitor.vue
  test/backend-test/test-rabbitmq.js
Labels: area:monitor

#5075 Last part of 2.0 (Update database migration and history retention)
  extra/reset-migrate-aggregate-table-state.js
  package.json
  server/database.js
  server/jobs/clear-old-data.js
  server/server.js
  server/uptime-calculator.js
Labels: priority:high, releaseblocker, area:core

#5259 docs: add slack username helptext
  src/components/notifications/Slack.vue
  src/lang/en.json
Labels: pr:please address review comments
