Repository louislam/uptime-kuma, pull requests merged in 2025-05, with the labels that each got.

#5813 Add SpugPush notification provider
  server/notification-providers/spugpush.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/SpugPush.vue
  src/components/notifications/index.js
  src/lang/en.json
Labels: pr:please address review comments

#5817 Add disable url option in notification Discord
  server/notification-providers/discord.js
  src/components/notifications/Discord.vue
  src/lang/en.json
Labels: pr:please address review comments

#5435 Add a public URL field for monitors and uses it on the status page
  db/knex_migrations/2025-05-09-0000-add-custom-url.js
  server/model/group.js
  server/model/monitor.js
  server/socket-handlers/status-page-socket-handler.js
  src/components/MonitorSettingDialog.vue
  src/components/PublicGroupList.vue
  src/lang/en.json
  test/e2e/specs/status-page.spec.js
Labels: pr:please address review comments

#5489 added SMTP monitor
  db/knex_migrations/2025-01-01-0000-add-smtp.js
  server/model/monitor.js
  server/monitor-types/smtp.js
  server/server.js
  server/uptime-kuma-server.js
  src/lang/en.json
  src/pages/EditMonitor.vue
Labels: A:monitor, pr:needs review

#5588 Enhanced ping monitor with advanced options (count, timeout, numeric)
  db/knex_migrations/2025-03-04-0000-ping-advanced-options.js
  server/model/monitor.js
  server/server.js
  server/util-server.js
  src/lang/en.json
  src/pages/EditMonitor.vue
  src/util.js
  src/util.ts
Labels: pr:depends on other

#5859 Flashduty IntegrationKey support Endpoint URL
  server/notification-providers/flashduty.js
  src/components/notifications/FlashDuty.vue
  src/lang/en.json
Labels: pr:please address review comments
