Repository louislam/uptime-kuma, pull requests merged in 2025-03, with the labels that each got.

#5464 feat: allow users to @People in DingTalk notifications
  server/notification-providers/dingding.js
  src/components/notifications/DingDing.vue
  src/lang/en.json
Labels: pr:depends on other

#5644 Do not use --production flag anymore
  package.json
Labels: pr:depends on other

#5637 feat: rework notification templating and add support for telegram
  server/notification-providers/notification-provider.js
  server/notification-providers/smtp.js
  server/notification-providers/telegram.js
  server/notification-providers/webhook.js
  src/components/TemplatedInput.vue
  src/components/TemplatedTextarea.vue
  src/components/notifications/SMTP.vue
  src/components/notifications/Telegram.vue
  src/components/notifications/Webhook.vue
  src/lang/en.json
Labels: pr:please address review comments

#5668 Add Telegram custom bot api server support
  server/notification-providers/telegram.js
  src/components/notifications/Telegram.vue
  src/lang/en.json
Labels: area:notifications, pr:please address review comments
