Repository louislam/uptime-kuma, pull requests merged in 2025-01, with the labels that each got.

#5573 fix: make sure that stripping backslashes for notification urls cannot cause catastophic backtracking (ReDOS)
  server/notification-providers/pushdeer.js
  server/notification-providers/whapi.js
Labels: priority:high, area:notifications

#5495 chore(deps): update nostr notification provider
  package-lock.json
  package.json
  server/notification-providers/nostr.js
Labels: area:notifications, type:enhance-existing, pr:depends on other

#5548 chore(deps): upgrade http/https/socks proxy agents
  package-lock.json
  package.json
  server/proxy.js
Labels: area:monitor, pr:depends on other

#5582 Modify the "Time" in the AliyunSMS to local time.
  server/notification-providers/aliyun-sms.js
Labels: question, pr:please address review comments
