Repository louislam/uptime-kuma, pull requests merged in 2025-04, with the labels that each got.

#5165 fix: remove modal when navigating back
  src/components/CreateGroupDialog.vue
  src/components/NotificationDialog.vue
  src/components/ProxyDialog.vue
  src/components/TagsManager.vue
Labels: question, A:core, pr:needs review

#5760 fix: Mattermost notification provider not sending service name
  server/notification-providers/mattermost.js
Labels: A:notifications, type:enhance-existing

#5771 Fix #5745: Some labels without value still show a 'null' value
  src/components/Tag.vue
Labels: pr:needs review

#5782 feat: Support for country flags emojis
  package-lock.json
  package.json
  src/App.vue
  src/assets/app.scss
  src/components/settings/About.vue
  src/lang/en.json
Labels: feature-request, A:status-page, A:settings, pr:please address review comments

#5774 fix(dashboard): prevent y-overlapping of tags by adding a gap #5773
  src/components/MonitorListItem.vue
  src/components/Tag.vue
Labels: A:status-page, pr:needs review

#5788 fix: Check password strength when resetting the password in CLI
  extra/reset-password.js
Labels: A:core, A:ui/ux, pr:please address review comments

#5241 feat: Extend the length of status bar and feed sufficient data
  server/routers/status-page-router.js
  src/components/MonitorListItem.vue
  src/components/PublicGroupList.vue
Labels: pr:depends on other

#5800 feat: Support SMSPlanet notification provider
  server/notification-providers/sms-planet.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/SMSPlanet.vue
  src/components/notifications/index.js
  src/lang/en.json
Labels: pr:depends on other

#5781 Added Pumble Notification
  server/notification-providers/pumble.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/Pumble.vue
  src/components/notifications/index.js
Labels: A:notifications, type:new, pr:depends on other

#5426 Pushover add UP/DOWN status sounds
  server/notification-providers/pushover.js
  src/components/notifications/Pushover.vue
Labels: pr:depends on other

#5769 fix: Add name to preparePreloadData call in sendNotification as a better fix for #5760
  server/model/monitor.js
  server/notification-providers/mattermost.js
Labels: A:notifications, type:enhance-existing, pr:please address review comments

#5756 Update SMSEagle support adding APIv2 and calls integration
  server/notification-providers/smseagle.js
  src/components/notifications/SMSEagle.vue
  src/lang/en.json
Labels: pr:depends on other

#5546 Add OneChat notification provider
  server/notification-providers/onechat.js
  server/notification.js
  src/components/NotificationDialog.vue
  src/components/notifications/OneChat.vue
  src/components/notifications/index.js
  src/lang/en.json
Labels: A:notifications, pr:needs review
